"""
Scholar Studio — Experiment Code Template Generator

Generates a skeleton PyTorch project from paper JSON data.
The AI assistant fills in the TODO sections.

CLI: python -m scholar exp-codegen <paper_id>
"""
import json
import re
from pathlib import Path
from typing import Optional

from . import config


# ===================================================================
# Hyperparameter extraction from sections text
# ===================================================================

HYPERPARAM_PATTERNS = {
    "learning_rate": [
        r"learning\s+rate\s*(?:of|is|=|:)\s*([\d.e\-]+)",
        r"lr\s*=\s*([\d.e\-]+)",
        r"Adam.*?lr\s*=\s*([\d.e\-]+)",
    ],
    "batch_size": [
        r"batch\s+size\s*(?:of|is|=|:)\s*(\d+)",
        r"batch\s*=\s*(\d+)",
    ],
    "epochs": [
        r"(\d+)\s+epochs",
        r"train\s+for\s+(\d+)\s+epochs",
        r"epochs\s*=\s*(\d+)",
    ],
    "optimizer": [
        r"optimizer\s*(?:is|=|:)\s*(\w+)",
        r"using\s+(\w+)\s+optimizer",
        r"optimized\s+by\s+(\w+)",
    ],
    "weight_decay": [
        r"weight\s+decay\s*(?:of|is|=|:)\s*([\d.e\-]+)",
    ],
    "warmup_steps": [
        r"warmup\s+(?:steps|steps)\s*(?:of|is|=|:)\s*(\d+)",
    ],
}


def extract_hyperparameters(sections: list[dict]) -> dict:
    """Extract hyperparameters from paper sections text."""
    full_text = " ".join(
        s.get("content", "") + " " + s.get("heading", "")
        for s in sections
    )
    params = {}
    for key, patterns in HYPERPARAM_PATTERNS.items():
        for pattern in patterns:
            match = re.search(pattern, full_text, re.IGNORECASE)
            if match:
                try:
                    val = match.group(1)
                    if key in ("batch_size", "epochs", "warmup_steps"):
                        params[key] = int(val)
                    elif key == "optimizer":
                        params[key] = val
                    else:
                        params[key] = float(val)
                except (ValueError, IndexError):
                    pass
                break
    return params


# ===================================================================
# Title to module name
# ===================================================================

def title_to_module_name(title: str) -> str:
    """Convert paper title to a Python-safe module name.
    
    "Attention Is All You Need" -> "attention_is_all_you_need"
    """
    if not title:
        return "untitled_model"
    cleaned = re.sub(r"[^a-zA-Z0-9\s]", "", title)
    return "_".join(w.lower() for w in cleaned.split()[:6]) if cleaned.strip() else "untitled_model"


# ===================================================================
# Template generators
# ===================================================================

def generate_model_py(formulas: list, title: str) -> str:
    """Generate model.py skeleton with formula comments."""
    module_name = title_to_module_name(title)
    class_name = module_name.title().replace("_", "") or "PaperModel"
    
    formula_comments = []
    for i, f in enumerate(formulas[:15]):
        latex = (f.get("latex") or "") if isinstance(f, dict) else str(f)
        label = (f.get("label") or "") if isinstance(f, dict) else ""
        label_str = f" [{label}]" if label else ""
        # Clean up latex for comment
        latex_clean = latex.replace("\n", " ").strip()[:200]
        formula_comments.append(f"    # Eq. {i+1}{label_str}: {latex_clean}")
    
    formulas_block = "\n".join(formula_comments) if formula_comments else "    # No formulas extracted from paper"
    
    return f'''"""
Model definition for: {title}

This is a TEMPLATE generated by Scholar Studio.
The AI agent should fill in the implementation based on the paper's method section.
"""
import torch
import torch.nn as nn


class {class_name}(nn.Module):
    """Model architecture for {title}.

    Key formulas from the paper:
{formulas_block}
    """

    def __init__(self, config: dict = None):
        super().__init__()
        self.config = config or {{}}

        # TODO: Define model layers based on paper's architecture description
        # Reference: Section 3 (Method) of the paper
        self.layers = nn.ModuleList()

    def forward(self, x):
        # TODO: Implement forward pass
        # Reference: Equations listed in class docstring
        return x


def create_model(config: dict = None) -> nn.Module:
    """Factory function to create model instance."""
    return {class_name}(config)


# Quick sanity check
if __name__ == "__main__":
    model = create_model()
    print(f"Parameters: {{sum(p.numel() for p in model.parameters()):,}}")
    x = torch.randn(1, 3, 224, 224)  # TODO: adjust input shape
    out = model(x)
    print(f"Output shape: {{out.shape}}")
'''


def generate_train_py(formulas: list, title: str) -> str:
    """Generate train.py skeleton."""
    loss_formulas = [f for f in formulas if isinstance(f, dict) and 
                     any(kw in ((f.get("latex") or "") + (f.get("label") or "")).lower() 
                         for kw in ["loss", "objective", "cost"])]
    
    loss_comment = ""
    if loss_formulas:
        lf = loss_formulas[0]
        loss_comment = f"    # Loss function from paper: {(lf.get('latex') or '')[:150]}"
    else:
        loss_comment = "    # TODO: Define loss function based on paper's training objective"
    
    return f'''"""
Training script for: {title}

This is a TEMPLATE generated by Scholar Studio.
"""
import argparse
import yaml
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from pathlib import Path

from model import create_model
from data import create_dataloader


def train_one_epoch(model, dataloader, optimizer, criterion, device):
    """Train for one epoch."""
    model.train()
    total_loss = 0.0
    for batch_idx, (inputs, targets) in enumerate(dataloader):
        inputs, targets = inputs.to(device), targets.to(device)
        
        optimizer.zero_grad()
        outputs = model(inputs)
{loss_comment}
        loss = criterion(outputs, targets)  # TODO: implement loss
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        if batch_idx % 100 == 0:
            print(f"Batch {{batch_idx}}/{{len(dataloader)}} - loss: {{loss.item():.4f}}")
    
    return total_loss / len(dataloader)


def evaluate(model, dataloader, criterion, device):
    """Evaluate model."""
    model.eval()
    total_loss = 0.0
    correct = 0
    total = 0
    with torch.no_grad():
        for inputs, targets in dataloader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            total_loss += loss.item()
            # TODO: implement metric calculation
            # print(f"accuracy: {{acc:.4f}}")
    
    return {{"loss": total_loss / len(dataloader)}}


def main():
    parser = argparse.ArgumentParser(description="Train {title[:50]}")
    parser.add_argument("--config", type=str, default="config.yaml")
    parser.add_argument("--mode", type=str, default="quick", choices=["quick", "full"])
    parser.add_argument("--gpu", action="store_true")
    args = parser.parse_args()

    with open(args.config) as f:
        config = yaml.safe_load(f)

    device = torch.device("cuda" if args.gpu and torch.cuda.is_available() else "cpu")
    print(f"Device: {{device}}, Mode: {{args.mode}}")

    model = create_model(config)
    model = model.to(device)

    # Quick mode: small synthetic data
    if args.mode == "quick":
        print("Quick mode: using synthetic data")
        # TODO: generate small synthetic dataset for sanity check
        dataloader = create_dataloader(config, mode="quick")
    else:
        dataloader = create_dataloader(config, mode="full")

    criterion = nn.CrossEntropyLoss()  # TODO: adjust based on paper
    optimizer = optim.Adam(
        model.parameters(),
        lr=config.get("learning_rate", 1e-4),
        weight_decay=config.get("weight_decay", 0.0),
    )

    epochs = config.get("epochs", 10) if args.mode == "full" else 2
    for epoch in range(epochs):
        train_loss = train_one_epoch(model, dataloader, optimizer, criterion, device)
        metrics = evaluate(model, dataloader, criterion, device)
        print(f"Epoch {{epoch+1}}/{{epochs}} - train_loss: {{train_loss:.4f}} - val_loss: {{metrics['loss']:.4f}}")

    # Save results
    results = {{"epoch": epochs, "final_loss": metrics["loss"]}}
    import json
    with open("results.json", "w") as f:
        json.dump(results, f, indent=2)
    print("Results saved to results.json")


if __name__ == "__main__":
    main()
'''


def generate_data_py() -> str:
    return '''"""
Data loading for experiment.

This is a TEMPLATE generated by Scholar Studio.
"""
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np


class PaperDataset(Dataset):
    """Dataset for the paper's experiment.
    
    TODO: Implement data loading based on the paper's experimental setup.
    Check the paper for:
    - Dataset name (e.g., ImageNet, CIFAR-10, GLUE)
    - Preprocessing steps
    - Train/val/test splits
    """

    def __init__(self, config: dict, mode: str = "train"):
        self.config = config
        self.mode = mode
        # TODO: Load and preprocess data
        self.data = []
        self.labels = []

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]


class SyntheticDataset(Dataset):
    """Synthetic dataset for quick sanity check."""

    def __init__(self, n_samples=100, input_shape=(3, 224, 224), n_classes=10):
        self.data = torch.randn(n_samples, *input_shape)
        self.labels = torch.randint(0, n_classes, (n_samples,))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]


def create_dataloader(config: dict, mode: str = "quick") -> DataLoader:
    """Create dataloader for training/evaluation."""
    batch_size = config.get("batch_size", 32)
    
    if mode == "quick":
        dataset = SyntheticDataset(n_samples=100)
    else:
        # TODO: Use real dataset
        dataset = PaperDataset(config, mode="train")
    
    return DataLoader(dataset, batch_size=batch_size, shuffle=True)
'''


def generate_evaluate_py() -> str:
    return '''"""
Evaluation script for experiment.

This is a TEMPLATE generated by Scholar Studio.
"""
import torch
import json
from pathlib import Path


def compute_metrics(predictions, targets):
    """Compute evaluation metrics.
    
    TODO: Implement metrics based on paper's evaluation section.
    Common metrics: accuracy, F1, BLEU, ROUGE, mAP, etc.
    """
    metrics = {}
    
    # Accuracy
    if len(predictions) > 0:
        pred_classes = predictions.argmax(dim=-1)
        metrics["accuracy"] = (pred_classes == targets).float().mean().item()
    
    # TODO: Add paper-specific metrics
    
    return metrics


def evaluate_model(model, dataloader, device="cpu"):
    """Run evaluation and return metrics."""
    model.eval()
    all_preds = []
    all_targets = []
    
    with torch.no_grad():
        for inputs, targets in dataloader:
            inputs = inputs.to(device)
            outputs = model(inputs)
            all_preds.append(outputs.cpu())
            all_targets.append(targets)
    
    all_preds = torch.cat(all_preds)
    all_targets = torch.cat(all_targets)
    
    metrics = compute_metrics(all_preds, all_targets)
    
    # Print metrics for parsing
    for name, value in metrics.items():
        print(f"{name}: {value:.4f}")
    
    return metrics


if __name__ == "__main__":
    # Quick evaluation
    from model import create_model
    from data import create_dataloader
    import yaml
    
    with open("config.yaml") as f:
        config = yaml.safe_load(f)
    
    model = create_model(config)
    dataloader = create_dataloader(config, mode="quick")
    metrics = evaluate_model(model, dataloader)
    
    with open("eval_results.json", "w") as f:
        json.dump(metrics, f, indent=2)
    print("Evaluation results saved to eval_results.json")
'''


def generate_config_yaml(hyperparams: dict, title: str) -> str:
    defaults = {
        "learning_rate": 1e-4,
        "batch_size": 32,
        "epochs": 100,
        "optimizer": "adam",
        "weight_decay": 0.0,
    }
    defaults.update(hyperparams)
    
    lines = [
        f"# Configuration for: {title}",
        f"# Auto-generated by Scholar Studio. Adjust as needed.",
        "",
        f"# Model",
        f"model_name: \"{title_to_module_name(title)}\"",
        "",
        f"# Training",
        f"learning_rate: {defaults['learning_rate']}",
        f"batch_size: {defaults['batch_size']}",
        f"epochs: {defaults['epochs']}",
        f"optimizer: {defaults['optimizer']}",
        f"weight_decay: {defaults['weight_decay']}",
        "",
        f"# Data",
        f"dataset: \"TODO\"",
        f"data_dir: \"./data\"",
        f"num_workers: 4",
        "",
        f"# Device",
        f"device: \"auto\"",
        f"seed: 42",
    ]
    
    if "warmup_steps" in defaults:
        lines.append(f"warmup_steps: {defaults['warmup_steps']}")
    
    return "\n".join(lines) + "\n"


def generate_requirements_txt() -> str:
    return """torch>=2.0
torchvision>=0.15
numpy>=1.24
pyyaml>=6.0
tqdm>=4.65
"""


def generate_readme_md(title: str, ulid: str, formulas: list, authors: list) -> str:
    formula_list = "\n".join(
        f"- Eq. {i+1}: `{(f.get('latex') or '')[:100]}`"
        for i, f in enumerate(formulas[:10])
        if isinstance(f, dict)
    )
    author_str = ", ".join(authors[:5]) if authors else "Unknown"
    
    return f"""# Experiment: {title}

## Paper Information
- **Title:** {title}
- **Paper ID:** {ulid}
- **Authors:** {author_str}

## File Structure
- `model.py` — Model architecture (TODO: implement based on paper's method section)
- `data.py` — Data loading (TODO: implement based on paper's dataset)
- `train.py` — Training script (skeleton with standard training loop)
- `evaluate.py` — Evaluation script (skeleton with metric computation)
- `config.yaml` — Hyperparameters (extracted from paper, adjust as needed)
- `requirements.txt` — Python dependencies

## Key Formulas from Paper
{formula_list if formula_list else "- No formulas extracted"}

## How to Run

```bash
# Install dependencies
pip install -r requirements.txt

# Quick mode (CPU + synthetic data, 2 epochs)
python train.py --config config.yaml --mode quick

# Full mode (may need GPU + real data)
python train.py --config config.yaml --mode full --gpu

# Evaluate
python evaluate.py
```

## Notes
- This is a TEMPLATE generated by Scholar Studio.
- The AI agent should fill in the TODO sections based on the paper.
- Quick mode uses synthetic data for sanity checking only.
- Do not claim "full reproduction" unless results match the paper.
"""


# ===================================================================
# Main generation function
# ===================================================================

def generate_experiment_template(paper_id: str, output_dir: Path = None) -> dict:
    """
    Generate experiment code template from paper JSON.
    
    Args:
        paper_id: Paper ID (ULID/arXiv/DOI/slug)
        output_dir: Output directory (default: config.EXPERIMENTS_DIR / <ULID>)
    
    Returns: {ulid, title, files_created, formulas_count, hyperparams}
    """
    from .id_resolver import resolve_id
    ulid = resolve_id(paper_id) or paper_id

    # Load paper data
    json_path = config.PARSED_DIR / f"{ulid}.json"
    if not json_path.exists():
        return {"error": f"Paper JSON not found: {json_path}"}

    data = json.loads(json_path.read_text(encoding="utf-8"))
    title = data.get("title", "Untitled")
    authors = data.get("authors", [])
    formulas = data.get("formulas", [])
    sections = data.get("sections", [])

    # Extract hyperparameters
    hyperparams = extract_hyperparameters(sections)

    # Create output directory
    if output_dir is None:
        output_dir = config.EXPERIMENTS_DIR / ulid
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate files
    files = {
        "model.py": generate_model_py(formulas, title),
        "data.py": generate_data_py(),
        "train.py": generate_train_py(formulas, title),
        "evaluate.py": generate_evaluate_py(),
        "config.yaml": generate_config_yaml(hyperparams, title),
        "requirements.txt": generate_requirements_txt(),
        "README.md": generate_readme_md(title, ulid, formulas, authors),
    }

    # Write files
    for filename, content in files.items():
        (output_dir / filename).write_text(content, encoding="utf-8")

    return {
        "ulid": ulid,
        "title": title,
        "files_created": list(files.keys()),
        "formulas_count": len(formulas),
        "hyperparams": hyperparams,
        "output_dir": str(output_dir),
    }
